### ISSUE TITLE
Different results for pages[].get()

### ISSUE THREAD

**Issue by jnario** [pmaupin/pdfrw#100] opened 2017-06-18 02:49 UTC
To begin with-- it's probable I'm using the page object incorrectly.   However, I'm having trouble reconciling different results between the standard REPL and IPython.

This example uses Python 3.6, but is equally reproducible with 2.7 and 3.5.

My expectation is the result that appears in the IPython sample below.  However, I cannot reproduce that result in the standard REPL.

I redacted the actual filename and URLs.

## REPL
```
>>> from pdfrw import PdfReader
>>> xpdf = PdfReader('<<< mypdf_file.pdf >>>')
>>> xx = xpdf.pages[0]
>>> xx.get('/Annots')
[(158, 0), (159, 0), (160, 0), (161, 0), (162, 0), (163, 0), (164, 0)]
```

## IPython
```
In [1]: from pdfrw import PdfReader
   ...: xpdf = PdfReader('<<< mypdf_file.pdf >>>')
   ...: xx = xpdf.pages[0]
   ...: xx.get('/Annots')
   ...: 
Out[1]: 
[{'/A': {'/S': '/URI',
   '/URI': '(<<< url-i-am-looking-for >>>)'},
  '/BS': {'/S': '/S', '/Type': '/Border', '/W': '0'},
  '/Border': ['0', '0', '0'],
  '/H': '/I',
  '/Rect': ['51.7', '616.2', '138.101', '630.5'],
  '/StructParent': '1',
  '/Subtype': '/Link',
  '/Type': '/Annot'},
 {'/A': {'/S': '/URI',
   '/URI': '(<<< url-i-am-looking-for >>>)'},
  '/BS': {'/S': '/S', '/Type': '/Border', '/W': '0'},
  '/Border': ['0', '0', '0'],
  '/H': '/I',
  '/Rect': ['52.55', '541.0', '177.472', '554.15'],
  '/StructParent': '2',
  '/Subtype': '/Link',
  '/Type': '/Annot'},
 {'/A': {'/S': '/URI',
   '/URI': '(<<< url-i-am-looking-for >>>)'},
  '/BS': {'/S': '/S', '/Type': '/Border', '/W': '0'},
  '/Border': ['0', '0', '0'],
  '/H': '/I',
  '/Rect': ['53.8999', '440.65', '145.0', '454.85'],
  '/StructParent': '3',
  '/Subtype': '/Link',
  '/Type': '/Annot'},
 {'/A': {'/S': '/URI',
   '/URI': '(<<< url-i-am-looking-for >>>)'},
  '/BS': {'/S': '/S', '/Type': '/Border', '/W': '0'},
  '/Border': ['0', '0', '0'],
  '/H': '/I',
  '/Rect': ['0.0', '792.0', '0.0', '792.0'],
  '/StructParent': '4',
  '/Subtype': '/Link',
  '/Type': '/Annot'},
 {'/A': {'/S': '/URI',
   '/URI': '(<<< url-i-am-looking-for >>>)'},
  '/BS': {'/S': '/S', '/Type': '/Border', '/W': '0'},
  '/Border': ['0', '0', '0'],
  '/H': '/I',
  '/Rect': ['52.55', '280.0', '118.567', '293.15'],
  '/StructParent': '5',
  '/Subtype': '/Link',
  '/Type': '/Annot'},
 {'/A': {'/S': '/URI',
   '/URI': '(<<< url-i-am-looking-for >>>)'},
  '/BS': {'/S': '/S', '/Type': '/Border', '/W': '0'},
  '/Border': ['0', '0', '0'],
  '/H': '/I',
  '/Rect': ['52.55', '175.5', '214.68', '188.65'],
  '/StructParent': '6',
  '/Subtype': '/Link',
  '/Type': '/Annot'},
 {'/A': {'/S': '/URI',
   '/URI': '(<<< url-i-am-looking-for >>>)'},
  '/BS': {'/S': '/S', '/Type': '/Border', '/W': '0'},
  '/Border': ['0', '0', '0'],
  '/H': '/I',
  '/Rect': ['0.0', '792.0', '0.0', '792.0'],
  '/StructParent': '7',
  '/Subtype': '/Link',
  '/Type': '/Annot'}]
```

**Comment by pmaupin** [comment] 2017-06-18 12:43
This is a duplicate of issue #98.

Please take a look at that.

I will fix this at some point, because it's obviously intuitive to use it that way (and several users are coming over from PyPDF2), but a regular string is not really a valid `PdfDict` key, even though it sorta kinda works sometimes.  The only valid `PdfDict` keys are `PdfName` objects.  If you really want to use `get()` you can use `PdfName.Annots` or `PdfName('/Annots')`, but the only reason to _ever_ use `get` would be for efficiency -- e.g. if you are not caching those `PdfName` objects for multiple `get()` operations, don't do it.

The _right_ way to do it is simply `xxx.Annots`.  This will always return `None` if `Annots` is not defined in the dict, because that's how dictionaries work in PDF files.

**Closed by pmaupin** 2017-06-18 12:43 UTC

**Comment by jnario** [comment] 2017-06-18 15:13
I actually took a closer look at #98 after I opened this one.  Sorry for the churn-- I was already refactoring based on the material in that thread.

Your comments on that issue and this issue are helpful-- thanks for the attention, and good luck on the project.

**Comment by pmaupin** [comment] 2017-06-18 15:19
No big deal, and you're welcome.  Hope pdfrw works for you.
