### ISSUE TITLE
AssertionError is PDFString is '<>'

### ISSUE THREAD

**Issue by a59** [pmaupin/pdfrw#88] opened 2017-04-13 21:49 UTC
If a PDFString s is '<>' then

s.decode()

raises an AssertionError.

**Comment by pmaupin** [comment] 2017-04-13 22:15
Thank you for the report.  I believe this was fixed in master by PR #81 a couple of weeks ago, and I just now added regression tests to verify it.  Please give additional details if you believe PdfStrings are still broken on the master branch.

**Comment by a59** [comment] 2017-04-24 19:59
I am still getting the AssertionError. Is there something I can check to make sure I am using the fixed code. (I cloned and installed the code from here.)

**Comment by pmaupin** [comment] 2017-04-24 22:57
This works for me:

```
$ git checkout master
Already on 'master'
Your branch is up-to-date with 'origin/master'.
$ git pull origin master
From https://github.com/pmaupin/pdfrw
 * branch            master     -> FETCH_HEAD
Already up-to-date.
$ python3.6
Python 3.6.1 (default, Mar 22 2017, 10:05:53) 
[GCC 5.4.1 20170304] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pdfrw
>>> pdfrw.__file__
'/home/pmaupin/projects/opensource/pdfrw/pdfrw/__init__.py'
>>> pdfrw.PdfString('<>').decode()
''
>>> 
$ python2
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pdfrw
>>> pdfrw.__file__
'pdfrw/__init__.py'
>>> pdfrw.PdfString('<>').decode()
u''
>>> pdfrw.PdfString('<>').to_bytes()
''
>>> 

```
So if it doesn't work for you, I'll need a better problem description, preferably with failing code, in order to figure out what's going on.

Thanks,
Pat

**Comment by a59** [comment] 2017-04-30 20:48
Thanks. Tried that. Then forcing a reinstall solved my problem.

**Closed** 2017-05-04 20:06 UTC
